// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyserviceClient is the client API for Myservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyserviceClient interface {
	Reverse(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*ReverseResponse, error)
	CheckEvenOdd(ctx context.Context, in *CheckEvenOddRequest, opts ...grpc.CallOption) (*CheckEvenOddResponse, error)
}

type myserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyserviceClient(cc grpc.ClientConnInterface) MyserviceClient {
	return &myserviceClient{cc}
}

func (c *myserviceClient) Reverse(ctx context.Context, in *ReverseRequest, opts ...grpc.CallOption) (*ReverseResponse, error) {
	out := new(ReverseResponse)
	err := c.cc.Invoke(ctx, "/proto.myservice/Reverse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myserviceClient) CheckEvenOdd(ctx context.Context, in *CheckEvenOddRequest, opts ...grpc.CallOption) (*CheckEvenOddResponse, error) {
	out := new(CheckEvenOddResponse)
	err := c.cc.Invoke(ctx, "/proto.myservice/CheckEvenOdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyserviceServer is the server API for Myservice service.
// All implementations must embed UnimplementedMyserviceServer
// for forward compatibility
type MyserviceServer interface {
	Reverse(context.Context, *ReverseRequest) (*ReverseResponse, error)
	CheckEvenOdd(context.Context, *CheckEvenOddRequest) (*CheckEvenOddResponse, error)
	mustEmbedUnimplementedMyserviceServer()
}

// UnimplementedMyserviceServer must be embedded to have forward compatible implementations.
type UnimplementedMyserviceServer struct {
}

func (UnimplementedMyserviceServer) Reverse(context.Context, *ReverseRequest) (*ReverseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reverse not implemented")
}
func (UnimplementedMyserviceServer) CheckEvenOdd(context.Context, *CheckEvenOddRequest) (*CheckEvenOddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEvenOdd not implemented")
}
func (UnimplementedMyserviceServer) mustEmbedUnimplementedMyserviceServer() {}

// UnsafeMyserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyserviceServer will
// result in compilation errors.
type UnsafeMyserviceServer interface {
	mustEmbedUnimplementedMyserviceServer()
}

func RegisterMyserviceServer(s grpc.ServiceRegistrar, srv MyserviceServer) {
	s.RegisterService(&Myservice_ServiceDesc, srv)
}

func _Myservice_Reverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyserviceServer).Reverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.myservice/Reverse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyserviceServer).Reverse(ctx, req.(*ReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Myservice_CheckEvenOdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEvenOddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyserviceServer).CheckEvenOdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.myservice/CheckEvenOdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyserviceServer).CheckEvenOdd(ctx, req.(*CheckEvenOddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Myservice_ServiceDesc is the grpc.ServiceDesc for Myservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Myservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.myservice",
	HandlerType: (*MyserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reverse",
			Handler:    _Myservice_Reverse_Handler,
		},
		{
			MethodName: "CheckEvenOdd",
			Handler:    _Myservice_CheckEvenOdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/myservice.proto",
}
