// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.2
// source: proto/myservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReverseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *ReverseRequest) Reset() {
	*x = ReverseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseRequest) ProtoMessage() {}

func (x *ReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseRequest.ProtoReflect.Descriptor instead.
func (*ReverseRequest) Descriptor() ([]byte, []int) {
	return file_proto_myservice_proto_rawDescGZIP(), []int{0}
}

func (x *ReverseRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ReverseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ReverseResponse) Reset() {
	*x = ReverseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseResponse) ProtoMessage() {}

func (x *ReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseResponse.ProtoReflect.Descriptor instead.
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return file_proto_myservice_proto_rawDescGZIP(), []int{1}
}

func (x *ReverseResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type CheckEvenOddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *CheckEvenOddRequest) Reset() {
	*x = CheckEvenOddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEvenOddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEvenOddRequest) ProtoMessage() {}

func (x *CheckEvenOddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEvenOddRequest.ProtoReflect.Descriptor instead.
func (*CheckEvenOddRequest) Descriptor() ([]byte, []int) {
	return file_proto_myservice_proto_rawDescGZIP(), []int{2}
}

func (x *CheckEvenOddRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type CheckEvenOddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsEven bool `protobuf:"varint,1,opt,name=is_even,json=isEven,proto3" json:"is_even,omitempty"`
}

func (x *CheckEvenOddResponse) Reset() {
	*x = CheckEvenOddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEvenOddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEvenOddResponse) ProtoMessage() {}

func (x *CheckEvenOddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEvenOddResponse.ProtoReflect.Descriptor instead.
func (*CheckEvenOddResponse) Descriptor() ([]byte, []int) {
	return file_proto_myservice_proto_rawDescGZIP(), []int{3}
}

func (x *CheckEvenOddResponse) GetIsEven() bool {
	if x != nil {
		return x.IsEven
	}
	return false
}

var File_proto_myservice_proto protoreflect.FileDescriptor

var file_proto_myservice_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26,
	0x0a, 0x0e, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x29, 0x0a, 0x0f, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x4f, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x2f, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x4f, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x45, 0x76, 0x65,
	0x6e, 0x32, 0x92, 0x01, 0x0a, 0x09, 0x6d, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3a, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x4f, 0x64, 0x64, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x4f, 0x64, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x4f, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x75, 0x6e, 0x67, 0x48, 0x6f, 0x6f, 0x6e, 0x30, 0x34,
	0x32, 0x32, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_myservice_proto_rawDescOnce sync.Once
	file_proto_myservice_proto_rawDescData = file_proto_myservice_proto_rawDesc
)

func file_proto_myservice_proto_rawDescGZIP() []byte {
	file_proto_myservice_proto_rawDescOnce.Do(func() {
		file_proto_myservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_myservice_proto_rawDescData)
	})
	return file_proto_myservice_proto_rawDescData
}

var file_proto_myservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_myservice_proto_goTypes = []interface{}{
	(*ReverseRequest)(nil),       // 0: proto.ReverseRequest
	(*ReverseResponse)(nil),      // 1: proto.ReverseResponse
	(*CheckEvenOddRequest)(nil),  // 2: proto.CheckEvenOddRequest
	(*CheckEvenOddResponse)(nil), // 3: proto.CheckEvenOddResponse
}
var file_proto_myservice_proto_depIdxs = []int32{
	0, // 0: proto.myservice.Reverse:input_type -> proto.ReverseRequest
	2, // 1: proto.myservice.CheckEvenOdd:input_type -> proto.CheckEvenOddRequest
	1, // 2: proto.myservice.Reverse:output_type -> proto.ReverseResponse
	3, // 3: proto.myservice.CheckEvenOdd:output_type -> proto.CheckEvenOddResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_myservice_proto_init() }
func file_proto_myservice_proto_init() {
	if File_proto_myservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_myservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_myservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_myservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEvenOddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_myservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEvenOddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_myservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_myservice_proto_goTypes,
		DependencyIndexes: file_proto_myservice_proto_depIdxs,
		MessageInfos:      file_proto_myservice_proto_msgTypes,
	}.Build()
	File_proto_myservice_proto = out.File
	file_proto_myservice_proto_rawDesc = nil
	file_proto_myservice_proto_goTypes = nil
	file_proto_myservice_proto_depIdxs = nil
}
